<a href="https://colab.research.google.com/github/Salonishah06/DataAnalysis/blob/main/DataAnalytics_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1=np.array([1,2,3])

print(arr1)

[1 2 3]


In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
print(arr1.shape)

(3,)


In [ ]:
arr1[2]=5
print(arr1)

[1 2 5]


In [ ]:
arr2=np.array([[1,2,3],[3,4,5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
print(arr2[0][2])

3


In [ ]:
print(type(arr2))
print(arr2.shape)

<class 'numpy.ndarray'>
(2, 3)


In [ ]:
arr2[1,2]

5

In [ ]:
arr2[1][-2]

4

In [ ]:
arrS=(['China','India','Australia','America'])
arrS


['China', 'India', 'Australia', 'America']

In [ ]:
arrR=np.arange(1,19,2)
arrR

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [ ]:
arrL=np.linspace(0,10,20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
arr=np.random.rand(10)
arr

array([0.37285883, 0.53459401, 0.07290491, 0.40720181, 0.05890973,
       0.34951789, 0.93935737, 0.064175  , 0.16076832, 0.94551714])

In [ ]:
arr=np.random.rand(3,4)
arr

array([[0.26766096, 0.1923014 , 0.46909551, 0.96950064],
       [0.278074  , 0.90790145, 0.70278839, 0.0938184 ],
       [0.05231299, 0.30296976, 0.43221318, 0.41872163]])

In [ ]:
print(np.zeros(10))
print('/n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr=[0,1,2]
print(np.repeat(arr,2))

[0 0 1 1 2 2]


In [ ]:
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [ ]:
#identity matrix
identity_matrix=np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.diag([1,2,3,4,5,6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [ ]:
arr=np.random.rand(5,5)
arr

array([[0.88269296, 0.23076519, 0.03195248, 0.44447707, 0.64972317],
       [0.28818088, 0.51189489, 0.09486084, 0.86831599, 0.97924848],
       [0.13001001, 0.92989327, 0.17022704, 0.72358024, 0.81070037],
       [0.85242517, 0.87949633, 0.52778641, 0.36861532, 0.81736577],
       [0.75788776, 0.15900239, 0.05524261, 0.45864779, 0.46965338]])

In [ ]:
np.diag(arr)

array([0.88269296, 0.51189489, 0.17022704, 0.36861532, 0.46965338])

In [ ]:
arr.ndim

2

In [ ]:
arr.size

25

In [ ]:
arr.shape

(5, 5)

In [ ]:
np.random.randint(-10,10,4)

array([ 7, -4,  8,  1])

In [ ]:
arr-10

array([[-9.11730704, -9.76923481, -9.96804752, -9.55552293, -9.35027683],
       [-9.71181912, -9.48810511, -9.90513916, -9.13168401, -9.02075152],
       [-9.86998999, -9.07010673, -9.82977296, -9.27641976, -9.18929963],
       [-9.14757483, -9.12050367, -9.47221359, -9.63138468, -9.18263423],
       [-9.24211224, -9.84099761, -9.94475739, -9.54135221, -9.53034662]])

In [ ]:
arr*2

array([[1.76538592, 0.46153038, 0.06390496, 0.88895414, 1.29944633],
       [0.57636177, 1.02378977, 0.18972168, 1.73663198, 1.95849695],
       [0.26002002, 1.85978654, 0.34045408, 1.44716047, 1.62140074],
       [1.70485033, 1.75899266, 1.05557281, 0.73723064, 1.63473154],
       [1.51577552, 0.31800477, 0.11048522, 0.91729558, 0.93930677]])

In [ ]:
arr/2

array([[0.44134648, 0.1153826 , 0.01597624, 0.22223854, 0.32486158],
       [0.14409044, 0.25594744, 0.04743042, 0.434158  , 0.48962424],
       [0.06500501, 0.46494664, 0.08511352, 0.36179012, 0.40535019],
       [0.42621258, 0.43974816, 0.2638932 , 0.18430766, 0.40868288],
       [0.37894388, 0.07950119, 0.0276213 , 0.2293239 , 0.23482669]])

In [ ]:
np.exp(arr)

array([[2.41740091, 1.25956345, 1.03246844, 1.55967438, 1.91501062],
       [1.33399858, 1.66844973, 1.09950584, 2.38289466, 2.66245459],
       [1.13883978, 2.53423869, 1.18557399, 2.06180175, 2.24948291],
       [2.34532777, 2.40968571, 1.69517572, 1.44573135, 2.26452669],
       [2.13376444, 1.17234075, 1.05679697, 1.58193343, 1.59943971]])

In [ ]:
np.log2(arr)

array([[-0.1800164 , -2.11550247, -4.96792836, -1.1698191 , -0.62210295],
       [-1.79495346, -0.9660805 , -3.39804357, -0.20370794, -0.03025312],
       [-2.94330539, -0.10486295, -2.55446786, -0.46677509, -0.30275929],
       [-0.23035491, -0.18525054, -0.9219739 , -1.43981207, -0.29094627],
       [-0.39994388, -2.65287967, -4.17807474, -1.1245414 , -1.09033169]])

In [ ]:
np.log10(arr)

array([[-0.05419034, -0.6368297 , -1.49549545, -0.35215064, -0.18727165],
       [-0.54033483, -0.29081921, -1.02291304, -0.0613222 , -0.0091071 ],
       [-0.88602321, -0.03156689, -0.76897145, -0.1405133 , -0.09113963],
       [-0.06934374, -0.05576597, -0.2775418 , -0.43342662, -0.08758355],
       [-0.12039511, -0.79859635, -1.25772582, -0.33852069, -0.32822254]])

In [ ]:
np.sin(arr)

array([[0.7724519 , 0.2287225 , 0.03194704, 0.42998582, 0.604966  ],
       [0.2842086 , 0.48983012, 0.09471863, 0.76324196, 0.83007852],
       [0.12964407, 0.80155613, 0.16940611, 0.66207208, 0.7247699 ],
       [0.75287876, 0.77041787, 0.5036222 , 0.36032411, 0.72934617],
       [0.68738888, 0.15833326, 0.05521452, 0.44273605, 0.45257723]])

In [ ]:
np.tan(arr)

array([[1.21631935, 0.23495065, 0.03196336, 0.47626146, 0.75976767],
       [0.29643275, 0.56184912, 0.0951464 , 1.18128289, 1.48853885],
       [0.1307475 , 1.34057525, 0.17189056, 0.88342221, 1.05192943],
       [1.14391583, 1.20842419, 0.58294734, 0.38627103, 1.06606981],
       [0.94643916, 0.16035603, 0.05529887, 0.49376576, 0.50752992]])

In [ ]:
np.sum(arr)

13.092645796405796

In [ ]:
np.sum(arr,axis=1)#axis =0 means all columns and axis=1 means all rows

array([2.23961087, 2.74250108, 2.76441093, 3.44568899, 1.90043393])

In [ ]:
np.min(arr,axis=0)




array([0.13001001, 0.15900239, 0.03195248, 0.36861532, 0.46965338])

In [ ]:
arr

array([[0.88269296, 0.23076519, 0.03195248, 0.44447707, 0.64972317],
       [0.28818088, 0.51189489, 0.09486084, 0.86831599, 0.97924848],
       [0.13001001, 0.92989327, 0.17022704, 0.72358024, 0.81070037],
       [0.85242517, 0.87949633, 0.52778641, 0.36861532, 0.81736577],
       [0.75788776, 0.15900239, 0.05524261, 0.45864779, 0.46965338]])

In [ ]:
np.max(arr,axis=1)

array([0.88269296, 0.97924848, 0.92989327, 0.87949633, 0.75788776])

In [ ]:
np.mean(arr,axis=0)

array([0.58223936, 0.54221041, 0.17601387, 0.57272728, 0.74533823])

In [ ]:
np.median(arr)

0.511894887418135

In [ ]:
np.std(arr)

0.3079687106868866

In [ ]:
np.var(arr)

0.09484472676214324

In [ ]:
arr[1:,2:3]

array([[0.09486084],
       [0.17022704],
       [0.52778641],
       [0.05524261]])

In [ ]:
np.sort(arr)

array([[0.03195248, 0.23076519, 0.44447707, 0.64972317, 0.88269296],
       [0.09486084, 0.28818088, 0.51189489, 0.86831599, 0.97924848],
       [0.13001001, 0.17022704, 0.72358024, 0.81070037, 0.92989327],
       [0.36861532, 0.52778641, 0.81736577, 0.85242517, 0.87949633],
       [0.05524261, 0.15900239, 0.45864779, 0.46965338, 0.75788776]])

In [ ]:
arr

array([[0.88269296, 0.23076519, 0.03195248, 0.44447707, 0.64972317],
       [0.28818088, 0.51189489, 0.09486084, 0.86831599, 0.97924848],
       [0.13001001, 0.92989327, 0.17022704, 0.72358024, 0.81070037],
       [0.85242517, 0.87949633, 0.52778641, 0.36861532, 0.81736577],
       [0.75788776, 0.15900239, 0.05524261, 0.45864779, 0.46965338]])

In [ ]:
arr.T

array([[0.88269296, 0.28818088, 0.13001001, 0.85242517, 0.75788776],
       [0.23076519, 0.51189489, 0.92989327, 0.87949633, 0.15900239],
       [0.03195248, 0.09486084, 0.17022704, 0.52778641, 0.05524261],
       [0.44447707, 0.86831599, 0.72358024, 0.36861532, 0.45864779],
       [0.64972317, 0.97924848, 0.81070037, 0.81736577, 0.46965338]])

In [ ]:
arr[:3,:].flatten()

array([0.88269296, 0.23076519, 0.03195248, 0.44447707, 0.64972317,
       0.28818088, 0.51189489, 0.09486084, 0.86831599, 0.97924848,
       0.13001001, 0.92989327, 0.17022704, 0.72358024, 0.81070037])

In [ ]:
arr=np.array([4,5,6,7])
arr

array([4, 5, 6, 7])

In [ ]:
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [ ]:
arr2=np.insert(arr,0,[1,2,3])
arr2

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr3=np.delete(arr2,[1,2])
arr3

array([1, 4, 5, 6, 7])

In [ ]:
arrC=arr3.copy()
arrC

array([1, 4, 5, 6, 7])

In [ ]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])
arr_cat=np.concatenate((arr1,arr2),axis=1)
print(arr_cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [ ]:
catv=np.vstack((arr1,arr2))

In [ ]:
print(catv)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
catH=np.hstack((arr1,arr2))

In [ ]:
print(catH)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [ ]:
arr=np.array([1,2,3,4,2,1,3,4,56])
np.unique(arr)

array([ 1,  2,  3,  4, 56])

In [ ]:
uniques,counts=np.unique(arr,return_counts=True)
print(uniques)
print(counts)

[ 1  2  3  4 56]
[2 2 2 2 1]


In [ ]:
#intersection,differentiation,neither
arr1=np.array([1,2,3,4,5,6,7])
arr2=np.array([3,4,5,6,7,9])
print(np.intersect1d(arr1,arr2))#what do they both have in common
print(np.union1d(arr1,arr2))#what are the unique values in both arrays
print(np.setdiff1d(arr1,arr2))#what is not in arr1 but not arr2
print(np.setxor1d(arr1,arr2))#what is there in 1 and not in 2 and vice versa

[3 4 5 6 7]
[1 2 3 4 5 6 7 9]
[1 2]
[1 2 9]
